/*
 * JSP generated by Resin-4.0.33 (built Wed, 19 Dec 2012 10:12:03 PST)
 */

package _jsp._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _compare__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html; charset=UTF-8");
    org.springframework.web.servlet.tags.form.FormTag _jsp_FormTag_0 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
String path = request.getContextPath();
            String basePath;
            if (request.getServerPort() == 80) {
                basePath = request.getScheme() + "://"
                        + request.getServerName() + path;
            } else {
                basePath = request.getScheme() + "://"
                        + request.getServerName() + ":"
                        + request.getServerPort() + path;
            }

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((basePath));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((basePath));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((basePath));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((basePath));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((basePath));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((basePath));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((basePath));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    _jsp_FormTag_0 = _jsp_state.get_jsp_FormTag_0(pageContext, _jsp_parent_tag);
    javax.servlet.jsp.JspWriter _jsp_writer2 = out;
    try {
      int _jspEval3 = _jsp_FormTag_0.doStartTag();
      if (_jspEval3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write(_jsp_string9, 0, _jsp_string9.length);
        _caucho_expr_0.print(out, _jsp_env, false);
        out.write(_jsp_string10, 0, _jsp_string10.length);
        _caucho_expr_1.print(out, _jsp_env, false);
        out.write(_jsp_string11, 0, _jsp_string11.length);
        _caucho_expr_2.print(out, _jsp_env, false);
        out.write(_jsp_string12, 0, _jsp_string12.length);
        _caucho_expr_3.print(out, _jsp_env, false);
        out.write(_jsp_string13, 0, _jsp_string13.length);
        _caucho_expr_4.print(out, _jsp_env, false);
        out.write(_jsp_string14, 0, _jsp_string14.length);
        _caucho_expr_5.print(out, _jsp_env, false);
        out.write(_jsp_string15, 0, _jsp_string15.length);
        _caucho_expr_6.print(out, _jsp_env, false);
        out.write(_jsp_string16, 0, _jsp_string16.length);
        _caucho_expr_7.print(out, _jsp_env, false);
        out.write(_jsp_string17, 0, _jsp_string17.length);
        _caucho_expr_8.print(out, _jsp_env, false);
        out.write(_jsp_string18, 0, _jsp_string18.length);
        _caucho_expr_9.print(out, _jsp_env, false);
        out.write(_jsp_string19, 0, _jsp_string19.length);
        _caucho_expr_10.print(out, _jsp_env, false);
        out.write(_jsp_string20, 0, _jsp_string20.length);
      }
      _jsp_FormTag_0.doEndTag();
    } catch (Throwable _jsp_exn_5) {
      pageContext.setWriter(_jsp_writer2);
      out = _jsp_writer2;
      _jsp_FormTag_0.doCatch(_jsp_exn_5);
    } finally {
      _jsp_FormTag_0.doFinally();
    }
    out.write(_jsp_string21, 0, _jsp_string21.length);
    out.print((basePath));
    out.write(_jsp_string22, 0, _jsp_string22.length);
    out.print((basePath));
    out.write(_jsp_string23, 0, _jsp_string23.length);
    _caucho_expr_11.print(out, _jsp_env, false);
    out.write(_jsp_string24, 0, _jsp_string24.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != 516923625575712947L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("jsp/compare.jsp"), -2212297334638913972L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("jsp/taglibs.jsp"), 5578382429526907488L, false);
    _caucho_depends.add(depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/D:/SOURCE_POOL/Exam-web/WebRoot/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring-form.tld"), -7844667629652253265L, false);
    _caucho_depends.add(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.springframework.web.servlet.tags.form.FormTag", 3927560123420998228L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.springframework.web.servlet.tags.form.FormTag _jsp_FormTag_0;

    final org.springframework.web.servlet.tags.form.FormTag get_jsp_FormTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_FormTag_0 == null) {
        _jsp_FormTag_0 = new org.springframework.web.servlet.tags.form.FormTag();
        _jsp_FormTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_FormTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_FormTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_FormTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_FormTag_0.setId("form-setting");
        _jsp_FormTag_0.setAction("#");
        _jsp_FormTag_0.setMethod("post");
        _jsp_FormTag_0.setModelAttribute("setting");
      }

      return _jsp_FormTag_0;
    }

    void release()
    {
      if (_jsp_FormTag_0 != null)
        _jsp_FormTag_0.release();
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
      manager.addTaglibFunctions(_jsp_functionMap, "fmt", "http://java.sun.com/jsp/jstl/fmt");
      manager.addTaglibFunctions(_jsp_functionMap, "fn", "http://java.sun.com/jsp/jstl/functions");
      manager.addTaglibFunctions(_jsp_functionMap, "sec", "http://www.springframework.org/security/tags");
      manager.addTaglibFunctions(_jsp_functionMap, "form", "http://www.springframework.org/tags/form");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
      _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.sourceDatabaseSetting.address}");
      _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.sourceDatabaseSetting.user}");
      _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.sourceDatabaseSetting.password}");
      _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.sourceDatabaseSetting.port}");
      _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.sourceDatabaseSetting.dbname}");
      _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.targetDatabaseSetting.address}");
      _caucho_expr_6 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.targetDatabaseSetting.user}");
      _caucho_expr_7 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.targetDatabaseSetting.password}");
      _caucho_expr_8 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.targetDatabaseSetting.port}");
      _caucho_expr_9 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.targetDatabaseSetting.dbname}");
      _caucho_expr_10 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${setting.includeTables}");
      _caucho_expr_11 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${basePath}");
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;
  private static com.caucho.el.Expr _caucho_expr_6;
  private static com.caucho.el.Expr _caucho_expr_7;
  private static com.caucho.el.Expr _caucho_expr_8;
  private static com.caucho.el.Expr _caucho_expr_9;
  private static com.caucho.el.Expr _caucho_expr_10;
  private static com.caucho.el.Expr _caucho_expr_11;

  private final static char []_jsp_string16;
  private final static char []_jsp_string3;
  private final static char []_jsp_string19;
  private final static char []_jsp_string17;
  private final static char []_jsp_string1;
  private final static char []_jsp_string10;
  private final static char []_jsp_string5;
  private final static char []_jsp_string15;
  private final static char []_jsp_string2;
  private final static char []_jsp_string24;
  private final static char []_jsp_string23;
  private final static char []_jsp_string20;
  private final static char []_jsp_string13;
  private final static char []_jsp_string4;
  private final static char []_jsp_string8;
  private final static char []_jsp_string12;
  private final static char []_jsp_string7;
  private final static char []_jsp_string0;
  private final static char []_jsp_string9;
  private final static char []_jsp_string14;
  private final static char []_jsp_string21;
  private final static char []_jsp_string18;
  private final static char []_jsp_string6;
  private final static char []_jsp_string11;
  private final static char []_jsp_string22;
  static {
    _jsp_string16 = "\">\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"target_pwd\">password</label> <input id=\"target_pwd\"\r\n						class=\"text\" type=\"password\" tabindex=\"7\" value=\"".toCharArray();
    _jsp_string3 = "/js/public.js\"></script>\r\n<script type=\"text/javascript\"\r\n	src=\"".toCharArray();
    _jsp_string19 = "\"\r\n						name=\"targetDatabaseSetting.dbname\">\r\n				</div>\r\n			</fieldset>\r\n			<div id=\"include-tables\">\r\n				<label for=\u201cinclude_tables\u201d>include tables</label><input\r\n					id=\"include_tables\" title=\"\u4ee5 ; \u9694\u5f00\" class=\"text\" tabindex=\"9\" value=\"".toCharArray();
    _jsp_string17 = "\" name=\"targetDatabaseSetting.password\" >\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"target_port\">port</label> <input id=\"target_port\"\r\n						class=\"text\" type=\"text\" tabindex=\"8\" value=\"".toCharArray();
    _jsp_string1 = "\r\n\r\n\r\n\r\n\r\n\r\n<meta http-equiv=\"pragma\" content=\"no-cache\" />\r\n<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n<meta http-equiv=\"expires\" content=\"0\">\r\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" />\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n<script type=\"text/javascript\"\r\n	src=\"".toCharArray();
    _jsp_string10 = "\"\r\n						name=\"sourceDatabaseSetting.address\" style=\"color: rgb(0, 0, 0);\">\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"source_user\">user</label> <input id=\"source_user\"\r\n						class=\"text\" type=\"text\" tabindex=\"2\" value=\"".toCharArray();
    _jsp_string5 = "/js/jquery.dynatree.min.js\"></script>\r\n\r\n\r\n<link type=\"text/css\" rel=\"stylesheet\"\r\n	href=\"".toCharArray();
    _jsp_string15 = "\"\r\n						name=\"targetDatabaseSetting.address\" style=\"color: rgb(0, 0, 0);\">\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"target_user\">user</label> <input id=\"target_user\"\r\n						class=\"text\" type=\"text\" tabindex=\"6\" name=\"targetDatabaseSetting.user\" value=\"".toCharArray();
    _jsp_string2 = "/js/jquery-1.7.2.min.js\"></script>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string24 = "/skin/dynatree/\",\r\n							children : [ {\r\n								title : '<img src=\"/skin/dynatree/diff.png\" />'\r\n										+ 'Tables' + '(Total:10,diff:7,miss:3)',\r\n								//isFolder : false,\r\n								icon : 'tables.ico',\r\n								children : [ {\r\n									title : '<img src=\"/skin/dynatree/diff.png\" />'\r\n											+ 'admin',\r\n									icon : 'table.ico',\r\n									//	isFolder : false,\r\n									children : [\r\n											{\r\n												title : '<img src=\"/skin/dynatree/diff.png\" />'\r\n														+ 'Columns'\r\n														+ '(Total:5,miss:3)',\r\n												icon : 'columns.ico',\r\n												//isFolder : false,\r\n												children : [\r\n														{\r\n															title : '<img src=\"/skin/dynatree/miss.png\" />'\r\n																	+ 'audit',\r\n															icon : 'column.ico',\r\n															diffContent : ''//TODO\r\n														},\r\n														{\r\n															title : '<img src=\"/skin/dynatree/miss.png\" />'\r\n																	+ 'creator',\r\n															icon : 'column.ico',\r\n															diffContent : ''//TODO\r\n														} ]\r\n											},\r\n											{\r\n												title : '<img src=\"/skin/dynatree/diff.png\" />'\r\n														+ 'Indexes'\r\n														+ '(Total:7,diff:7)',\r\n												icon : 'indexes.ico',\r\n											//isFolder : false,\r\n											} ]\r\n								} ]\r\n							} ]\r\n						});\r\n	});\r\n</script>\r\n</html>".toCharArray();
    _jsp_string23 = "/setting/save?isChanged=\"+isChanged);\r\n	$(\"#form-setting\").submit();\r\n	return true;\r\n}\r\n\r\n	//TODO \u5f39\u4e00\u4e2a\u6846\r\n	$(function() {\r\n		easyDialog.open({\r\n			container : 'setting',\r\n		//autoClose : 10000\r\n		});\r\n\r\n		// Attach the dynatree widget to an existing <div id=\"tree\"> element\r\n		// and pass the tree options as an argument to the dynatree() function:\r\n		$(\"#tree\")\r\n				.dynatree(\r\n						{\r\n							onCreate : function(node, span) {\r\n								//alert($(node.span).find('img'));\r\n								//$(node.span).find('a').after($('<img src=\"/skin/dynatree/equal.png\" />'));\r\n								//node.data.title='<img src=\"/skin/dynatree/equal.png\" />'+node.data.title;\r\n								//$(node.span).css({'background-image':'/skin/dynatree/equal.png',position:'absolute'})\r\n							},\r\n							onPostInit : function(dtnode) {\r\n								//alert('init');\r\n								//node.data.title='<img src=\"/skin/dynatree/equal.png\" />'+node.data.title;\r\n								//$(node.span).find('img').after($('<img src=\"/skin/dynatree/equal.png\" />'));\r\n							},\r\n							imagePath : \"".toCharArray();
    _jsp_string20 = "\"\r\n					name=\"includeTables\" />\r\n			</div>\r\n			<div class='btns'>\r\n				<div class=\"item1\" style=\"float: left\">\r\n					<input class=\"bn-submit\" type=\"submit\" tabindex=\"10\"\r\n						value=\"confirm\" onclick=\"return check(true);\">\r\n				</div>\r\n				<div class=\"item1\" style=\"float: right\">\r\n					<input class=\"bn-submit\" type=\"submit\" onclick='return check(false)'\r\n						tabindex=\"10\" value=\"cancel\">\r\n				</div>\r\n			</div>\r\n		".toCharArray();
    _jsp_string13 = "\"name=\"sourceDatabaseSetting.port\">\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"source_database\">database</label> <input\r\n						id=\"source_database\" class=\"text\" type=\"text\" tabindex=\"4\"\r\n						value=\"".toCharArray();
    _jsp_string4 = "/js/jquery-ui-1.8.23.custom.min.js\"></script>\r\n<script type=\"text/javascript\"\r\n	src=\"".toCharArray();
    _jsp_string8 = "/skin/main.css\" />\r\n\r\n<title>\u6570\u636e\u5e93schema\u6bd4\u8f83\u8bbe\u7f6e</title>\r\n</head>\r\n<body>\r\n	\r\n	<div id=\"setting\" class=\"setting\">\r\n		<div class=\"title\">\r\n			<strong>Compare Setting</strong>\r\n		</div>\r\n		".toCharArray();
    _jsp_string12 = "\"name=\"sourceDatabaseSetting.password\">\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"source_port\">port</label> <input id=\"source_port\"\r\n						class=\"text\" type=\"text\" tabindex=\"4\" value=\"".toCharArray();
    _jsp_string7 = "/skin/easydialog/easydialog.css\" />\r\n<link type=\"text/css\" rel=\"stylesheet\"\r\n	href=\"".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n".toCharArray();
    _jsp_string9 = "\r\n			<fieldset title=\"Source\" style=\"float: left\">\r\n				<legend>Source</legend>\r\n				<div class=\"item\">\r\n					<label for=\"source_adress\">address</label> <input\r\n						id=\"source_adress\" type=\"text\" tabindex=\"1\" value=\"".toCharArray();
    _jsp_string14 = "\" name=\"sourceDatabaseSetting.dbname\">\r\n				</div>\r\n			</fieldset>\r\n			<fieldset title=\"Target\" style=\"float: right\">\r\n				<legend>Target</legend>\r\n				<div class=\"item\">\r\n					<label for=\"target_adress\">address</label> <input\r\n						id=\"target_adress\" type=\"text\" tabindex=\"5\"value=\"".toCharArray();
    _jsp_string21 = "\r\n	</div>\r\n\r\n</body>\r\n<script type=\"text/javascript\" src=\"".toCharArray();
    _jsp_string18 = "\" name=\"targetDatabaseSetting.port\">\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"target_database\">database</label> <input\r\n						id=\"target_database\" class=\"text\" type=\"text\" tabindex=\"4\" value=\"".toCharArray();
    _jsp_string6 = "/skin/dynatree/ui.dynatree.css\" />\r\n<link type=\"text/css\" rel=\"stylesheet\"\r\n	href=\"".toCharArray();
    _jsp_string11 = "\" name=\"sourceDatabaseSetting.user\">\r\n				</div>\r\n				<div class=\"item\">\r\n					<label for=\"source_pwd\">password</label> <input id=\"source_pwd\"\r\n						class=\"text\" type=\"password\" tabindex=\"3\" value=\"".toCharArray();
    _jsp_string22 = "/js/easydialog.min.js\"></script>\r\n<script type=\"text/javascript\">\r\nfunction check(isChanged){\r\n	$(\"#form-setting\").attr(\"action\", \"".toCharArray();
  }
}
